# Example usage of Swift Coverage Action
# Place this file in your repository's .github/workflows/ folder
#
# For latest version, replace @0.1.0 with @main
# For stability, pin to a specific version like @0.1.0

name: Test and Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  coverage:
    permissions:
      contents: read
      pull-requests: write  # Required for PR comments
      issues: write         # Required for PR comments
    uses: oleksiikolomiietssnapp/swift-coverage-action/.github/workflows/swift-coverage.yml@0.1.0
    with:
      # Basic configuration
      macos-version: "latest"               # Optional: "latest", "15", "14"
      xcode-version: "16.3"                 # Optional: specific version or system default
      working-directory: "."                # Optional: defaults to root

      # Project settings
      project-name-override: "MyProject"    # Optional: defaults to repo name
      source-path-override: "MyProject/Sources"  # Optional: custom source path

      # PR comments
      coverage-comment-header: "### 📊 Coverage"  # Optional: custom header
      post-comment: true                    # Optional: false for multi-job combined comments
      job-name: "Main Coverage"             # Optional: used in combined reports
      skip-label: "skip-coverage"           # Optional: PR label to skip execution

      # Quality threshold (when set, enables quality indicators)
      coverage-threshold: "80"              # Optional: e.g., "80" (leave empty to disable)
      fail-on-low-coverage: false           # Optional: fail if below threshold

  # Optional: Use coverage output in other jobs
  post-coverage:
    needs: coverage
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Print coverage
        run: echo "Coverage is ${{ needs.coverage.outputs.coverage-percentage }}%"
