# Example usage of Swift Coverage Action
# Place this file in your repository's .github/workflows/ folder
#
# For latest version, replace @0.1.0 with @main
# For stability, pin to a specific version like @0.1.0

name: Test and Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  coverage:
    uses: oleksiikolomiietssnapp/swift-coverage-action/.github/workflows/swift-coverage.yml@0.1.0
    with:
      xcode-version: "16.3"
      # Optional: Override project name (defaults to repository name)
      # project-name-override: "MyCustomProject"
      # Optional: Override source path pattern
      # source-path-override: "MyProject/Sources"
      # Optional: Customize coverage comment header
      # coverage-comment-header: "### 📊 Test Coverage "
      # Optional: Label to skip workflow (defaults to "skip-coverage")
      # skip-label: "skip-coverage"

  # Optional: Use coverage output in other jobs
  post-coverage:
    needs: coverage
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Print coverage
        run: echo "Coverage is ${{ needs.coverage.outputs.coverage-percentage }}%"
