name: Test Sample Multi-Target Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Allow manual triggering

jobs:
  coverage-default:
    name: "Coverage (default: macOS latest, Xcode system)"
    uses: ./.github/workflows/swift-coverage.yml
    with:
      project-name-override: "SampleMultiTarget"
      working-directory: "./sample"
      post-comment: false
      job-name: "macOS latest + Xcode system"

  coverage-macos-26:
    name: "Coverage (macOS 26, Xcode system)"
    uses: ./.github/workflows/swift-coverage.yml
    with:
      macos-version: "26"
      project-name-override: "SampleMultiTarget"
      working-directory: "./sample"
      post-comment: false
      job-name: "macOS 26 + Xcode system"

  coverage-xcode-16-3:
    name: "Coverage (macOS latest, Xcode 16.3)"
    uses: ./.github/workflows/swift-coverage.yml
    with:
      xcode-version: "16.3"
      project-name-override: "SampleMultiTarget"
      working-directory: "./sample"
      post-comment: false
      job-name: "macOS latest + Xcode 16.3"

  prepare-combined-comment:
    name: "Prepare Combined Comment Data"
    needs: [coverage-default, coverage-macos-26, coverage-xcode-16-3]
    runs-on: ubuntu-latest
    outputs:
      jobs-json: ${{ steps.prepare.outputs.jobs-json }}
    steps:
      - id: prepare
        run: |
          JOBS_JSON='[
            {
              "name": "${{ needs.coverage-default.outputs.job-name }}",
              "coverage": "${{ needs.coverage-default.outputs.coverage-percentage }}",
              "table": ${{ toJSON(needs.coverage-default.outputs.coverage-table) }}
            },
            {
              "name": "${{ needs.coverage-macos-26.outputs.job-name }}",
              "coverage": "${{ needs.coverage-macos-26.outputs.coverage-percentage }}",
              "table": ${{ toJSON(needs.coverage-macos-26.outputs.coverage-table) }}
            },
            {
              "name": "${{ needs.coverage-xcode-16-3.outputs.job-name }}",
              "coverage": "${{ needs.coverage-xcode-16-3.outputs.coverage-percentage }}",
              "table": ${{ toJSON(needs.coverage-xcode-16-3.outputs.coverage-table) }}
            }
          ]'
          echo "jobs-json<<EOF" >> $GITHUB_OUTPUT
          echo "$JOBS_JSON" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  post-coverage-comment:
    name: "Post Combined Coverage Comment"
    needs: [prepare-combined-comment]
    permissions:
      pull-requests: write
    uses: ./.github/workflows/swift-coverage-combined.yml
    with:
      jobs-json: ${{ needs.prepare-combined-comment.outputs.jobs-json }}
      comment-header: "## 📊 Sample Multi-Target Coverage Report"