name: Test Sample (Single Target)

on:
  workflow_call:

jobs:
  coverage:
    permissions:
      contents: read
      pull-requests: write
      issues: write
    uses: ./.github/workflows/swift-coverage.yml
    with:
      macos-version: "latest"
      xcode-version: ""
      working-directory: "./sample-single-target"
      coverage-comment-header: "### 📊 Single Target Coverage"
      post-comment: true
