name: Test Sample (Multiple Jobs)

on:
  workflow_call:

jobs:
  coverage-swift-6-0:
    name: "Coverage (Swift 6.0, Xcode 16.4, macOS 15)"
    uses: ./.github/workflows/swift-coverage.yml
    with:
      macos-version: "15"
      xcode-version: "16.4"
      project-name-override: "SampleMultiTarget"
      working-directory: "./sample"
      post-comment: false
      job-name: "Swift 6.0 (Xcode 16.4, macOS 15)"

  coverage-swift-6-1:
    name: "Coverage (Swift 6.1, Xcode 26.0, macOS 15)"
    uses: ./.github/workflows/swift-coverage.yml
    with:
      macos-version: "15"
      xcode-version: "26.0"
      project-name-override: "SampleMultiTarget"
      working-directory: "./sample"
      post-comment: false
      job-name: "Swift 6.1 (Xcode 26.0, macOS 15)"

  coverage-swift-6-2:
    name: "Coverage (Swift 6.2, Xcode 26.1, macOS 26)"
    uses: ./.github/workflows/swift-coverage.yml
    with:
      macos-version: "26"
      xcode-version: "26.1"
      project-name-override: "SampleMultiTarget"
      working-directory: "./sample"
      post-comment: false
      job-name: "Swift 6.2 (Xcode 26.1, macOS 26)"

  post-coverage-comment:
    name: "Post Combined Coverage Comment"
    if: github.event_name == 'pull_request'
    needs: [coverage-swift-6-0, coverage-swift-6-1, coverage-swift-6-2]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/github-script@v7
        with:
          script: |
            const script = require('./.github/scripts/post-combined-coverage-comment.js');

            const jobOutputs = [
              {
                name: "${{ needs.coverage-swift-6-0.outputs.job-name }}",
                coverage: "${{ needs.coverage-swift-6-0.outputs.coverage-percentage }}",
                table: `${{ needs.coverage-swift-6-0.outputs.coverage-table }}`
              },
              {
                name: "${{ needs.coverage-swift-6-1.outputs.job-name }}",
                coverage: "${{ needs.coverage-swift-6-1.outputs.coverage-percentage }}",
                table: `${{ needs.coverage-swift-6-1.outputs.coverage-table }}`
              },
              {
                name: "${{ needs.coverage-swift-6-2.outputs.job-name }}",
                coverage: "${{ needs.coverage-swift-6-2.outputs.coverage-percentage }}",
                table: `${{ needs.coverage-swift-6-2.outputs.coverage-table }}`
              }
            ];

            await script({github, context, jobOutputs});
