name: Test Sample (Combined Multi-Config)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Allow manual triggering
  workflow_call:
    inputs:
      runs: false

jobs:
  coverage-default:
    name: "Coverage (default: macOS latest, Xcode system)"
    if: ${{ inputs.runs }}
    uses: ./.github/workflows/swift-coverage.yml
    with:
      project-name-override: "SampleMultiTarget"
      working-directory: "./sample"
      post-comment: false
      job-name: "macOS latest + Xcode system"

  coverage-macos-26:
    name: "Coverage (macOS 26, Xcode system)"
    if: ${{ inputs.runs }}
    uses: ./.github/workflows/swift-coverage.yml
    with:
      macos-version: "26"
      project-name-override: "SampleMultiTarget"
      working-directory: "./sample"
      post-comment: false
      job-name: "macOS 26 + Xcode system"

  coverage-xcode-16-3:
    name: "Coverage (macOS latest, Xcode 16.3)"
    if: ${{ inputs.runs }}
    uses: ./.github/workflows/swift-coverage.yml
    with:
      xcode-version: "16.3"
      project-name-override: "SampleMultiTarget"
      working-directory: "./sample"
      post-comment: false
      job-name: "macOS latest + Xcode 16.3"

  post-coverage-comment:
    name: "Post Combined Coverage Comment"
    if: github.event_name == 'pull_request'
    needs: [coverage-default, coverage-macos-26, coverage-xcode-16-3]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            // Build coverage sections from job outputs
            const sections = [];

            const job1Name = "${{ needs.coverage-default.outputs.job-name }}";
            const job1Coverage = "${{ needs.coverage-default.outputs.coverage-percentage }}";
            const job1Table = `${{ needs.coverage-default.outputs.coverage-table }}`;
            if (job1Name && job1Coverage) {
              sections.push({ name: job1Name, coverage: job1Coverage, table: job1Table });
            }

            const job2Name = "${{ needs.coverage-macos-26.outputs.job-name }}";
            const job2Coverage = "${{ needs.coverage-macos-26.outputs.coverage-percentage }}";
            const job2Table = `${{ needs.coverage-macos-26.outputs.coverage-table }}`;
            if (job2Name && job2Coverage) {
              sections.push({ name: job2Name, coverage: job2Coverage, table: job2Table });
            }

            const job3Name = "${{ needs.coverage-xcode-16-3.outputs.job-name }}";
            const job3Coverage = "${{ needs.coverage-xcode-16-3.outputs.coverage-percentage }}";
            const job3Table = `${{ needs.coverage-xcode-16-3.outputs.coverage-table }}`;
            if (job3Name && job3Coverage) {
              sections.push({ name: job3Name, coverage: job3Coverage, table: job3Table });
            }

            // Build comment
            let comment = '## 📊 Sample Coverage Report\n\n';

            sections.forEach(section => {
              comment += '### ' + section.name + ' - ' + section.coverage + '%\n\n';
              comment += section.table + '\n\n';
            });

            comment += '---\n_Generated by [Swift Coverage Action](https://github.com/oleksiikolomiietssnapp/swift-coverage-action)_';

            // Delete old comments
            const comments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
            });

            const botComments = comments.data.filter(c => c.body.includes('## 📊 Sample Coverage Report'));
            for (const c of botComments) {
              await github.rest.issues.deleteComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: c.id,
              });
            }

            // Post new comment
            await github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment,
            });