name: Test and Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  coverage:
    uses: owner/swift-coverage-action/blob/main/.github/workflows/swift-coverage.yml@main
