name: Test and Coverage

 on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  coverage:
  
    uses: oleksiikolomiietssnapp/swift-coverage-action/blob/main/.github/workflows/swift-coverage.yml@main
